app:
   name: "web_app"
   mode: "dev"
   port: 18081
   version: "0.0.1"
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "root"
  dbname: "sql_test"
  max_open_cons: 200
  max_idle_cons: 50
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 100
snowflake:
  startTime: "2022-11-17"
  machineID: 1